[package]
name = "swift_to_plant_uml_converter"
version = "0.1.0"
authors = ["Radoslaw Cieciwa <radoslaw.cieciwa@corp.badoo.com>"]

[dependencies]
serde_json = "1.0"

[[bin]]
name = "swift_to_plant_umlconverter"
path = "main.rs"
